import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Linkedin, Github } from 'lucide-react';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="flex flex-row justify-between items-center p-6 w-full bg-violet-300">
        <Link href={"/"}>
            luis`s personal blog
        </Link>
          <div className="flex flex-row gap-4">
              <Link href="https://github.com/luis-ota/luis-blog">
                  <Github />
            </Link>
              <Link href="https://linkedin.com/in/luis-ota/">
                  <Linkedin />
              </Link>
          </div>
      </header>
        {children}
      </body>
    </html>
  );
}
